### ISSUE TITLE
Silencing warning

### ISSUE THREAD

**Issue by ericpre** [LumiSpy/eBEAM2024-Tutorial#3]
@jlaehne, what are the warnings that need silencing? Are there warning that are not appropriate or need to move a logger with a INFO level?
It is not a good practise to filter warning and it is not great (not a good example!) that this is the first thing that people runs in a tutorial.

![image](https://github.com/user-attachments/assets/43115518-2888-4445-961e-cb8a9725a51a)

**Comment by jlaehne** [comment]
Good point, at some tutorial last year, I was having issues with some function throwing a long list of warnings ... but that seems solved now, so I'll remove the silencing.

**Comment by jlaehne** [comment]
Currently, there is an upstream warning for the `remove_background` function (Notebook 1):
```.../lib/python3.11/site-packages/jupyter_client/session.py:721: UserWarning: Message serialization failed with:
Out of range float values are not JSON compliant
Supporting this message is deprecated in jupyter-client 7, please make sure your message is JSON-compliant
  content = self.pack(content)```

Also the `spikes_removal_tool` (Notebook 2) gives a warning when not adding any additional parameters:
```WARNING | Hyperspy | Estimated number of bins using `bins='fd'` is too large (5275). Capping the number of bins at `max_num_bins=1000`. Consider using an alternative method for calculating the bins such as `bins='scott'`, or increasing the value of the `max_num_bins` keyword argument. (hyperspy.misc.hist_tools:97)```

**Comment by ericpre** [comment]
> ```
> Out of range float values are not JSON compliant
> Supporting this message is deprecated in jupyter-client 7, please make sure your message is JSON-compliant
>   content = self.pack(content)
> ```
>
> ```
> Also the `spikes_removal_tool` (Notebook 2) gives a warning when not adding any additional parameters:
> ```WARNING | Hyperspy | Estimated number of bins using `bins='fd'` is too large (5275). Capping the number of bins at `max_num_bins=1000`. Consider using an alternative method for calculating the bins such as `bins='scott'`, or increasing the value of the `max_num_bins` keyword argument. (hyperspy.misc.hist_tools:97)```
> ```

Yes, they need fixing too:
- the first one is not obvious how to fix, the initial value of `nan` for the interval needs to be changed that makes the jupyter client happy and that is compatible with traits...
- the second one it may be worth trying another method to estimate the number of bins or simply using a fix number of bins.
